DROP TABLE USER;

CREATE TABLE IF NOT EXISTS USER ( ID INT NOT NULL AUTO_INCREMENT, PASSWORD VARCHAR(20), EMAIL VARCHAR(20));
INSERT INTO USER (PASSWORD, EMAIL) VALUES ('password', 'test1@test.co.jp');
INSERT INTO USER (PASSWORD, EMAIL) VALUES ('password', 'test2@test.co.jp');